cse408ebay/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
import customer
import global_controller.views as global_view
import customer.views as customer_views
import global_controller.authentication_module
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', global_view.home, name='global_home'),
    path('customer/', include('customer.urls', namespace='customer')),
    path('employee/', include('employee.urls', namespace='employee')),
    path('seller/', include('seller.urls', namespace='seller')),
    path('deliveryman/', include('deliveryman.urls', namespace='deliveryman')),

    path('login/', global_controller.authentication_module.logIn, name='login'),
    path('register/', global_controller.authentication_module.register, name='register'),
    path('seller_register/', global_controller.authentication_module.seller_register, name='seller_register'),
    path("logout/", global_controller.authentication_module.logout_request, name="logout"),
    path("product-details/<slug:inventory_id>", global_view.product_details, name="product-details"),
    path("auction-product-details/<slug:auction_id>", global_view.auction_product_details,
         name="auction-product-details"),
    path("add_to_cart/", global_view.add_to_cart, name="add_to_cart"),
    path('auction/', global_view.auction_home, name='auction_home'),
    # customer stuffs
    path("buy_product/", customer.views.buy_product, name="buy_product"),
    path("seller_register/get_location_from_coordinate/",
         global_controller.authentication_module.get_address_from_coordinate, name='coordinate-to-address'),
    path("send-mail", global_controller.authentication_module.test_mail, name='send-mail'),
    path("place-bid", global_controller.views.place_bid, name='place-bid'),
    path("search", global_controller.views.search_module, name='search'),

    path("category/<slug:category_name>", global_controller.views.category_module, name='category'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path, include
from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.load_customer, name='home'),
    path('order_history/', views.load_order_history, name='order_history'),
    path('product_status/', views.load_product_status, name='product_status'),
    path('remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('update_to_cart/', views.update_to_cart, name='update_to_cart'),
    path('recharge_wallet/', views.recharge_wallet, name='recharge_wallet'),
    path('change-info/', views.change_info, name='change_info'),
    path('transactions/', views.transactions, name='transactions'),
]

deliveryman/urls.py
from django.urls import path, include
from . import views

app_name = 'deliveryman'

urlpatterns = [

    path('', views.load_deliveryman, name='home_empty'),
    path('home/', views.load_deliveryman, name='home'),
    path('delivery-details/', views.delivery_details_of_customer, name='delivery-details'),
    path('delivery-details/authenticate-customer/', views.authenticate_customer, name='authenticate-customer'),
]

employee/urls.py
from django.urls import path, include
from . import views

app_name = 'employee'

urlpatterns = [
    path('', views.load_employee, name='home'),
    path('receiveglobal/', views.load_employee2, name='shipmentreceive'),
    path('sendglobal/', views.load_sending_global, name='shipmentsend'),
    path('sendlocal/', views.load_sending_local, name='localdelivery'),
    path('accept/', views.accept_order),
    path('reject/', views.reject_order),
    
]

seller/urls.py
from django.urls import path, include
from . import views

app_name = 'seller'

urlpatterns = [
    path('', views.load_inventory, name='home'),
    path("test_function/", views.test_functioon, name="test_function"),
    path("order_history/", views.order_history, name="order_history"),
    path("current_order/", views.current_order, name="current_order"),
    path("add_products/", views.add_products, name="add_products"),
    path("auction/", views.auction, name="auction"),
    path("wallet_to_bank/", views.wallet_to_bank, name="wallet_to_bank"),
    path("current_order/confirm_deliveryman/", views.confirm_deliveryman, name="confirm_deliveryman"),
    path("product_register/", views.product_register, name="product_register"),
    path("transcation-history/", views.transaction_history, name="transaction-history"),
    path("auction-multiple-product/", views.auction_multiple_product, name="auction-multiple-product"),
    path("restock-inventory/", views.restock_inventory, name="restock-inventory"),

]

templates/base/customer-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Customer</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>


    <link rel="stylesheet" href="{% static 'customer/css/change-account_info.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


    <link rel="stylesheet" href="{% static '/global_controller/css/base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">

{% include 'base/popup_notification.html' %}

<style>
    /* Chrome, Safari, Edge, Opera */
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    /* Firefox */
    input[type=number] {
        -moz-appearance: textfield;
    }
</style>


<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'global_home' %}">Bengal Bay</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <span class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">

        </span>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <a type="button" class="btn btn-danger" href="{% url 'logout' %}"><i class="bi bi-box-arrow-left me-2"></i>Log
            Out</a>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">

                    <a class="nav-link" href="{% url 'customer:home' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-house"></i></div>
                        Home
                    </a>

                    <a class="nav-link" href="{% url 'customer:order_history' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-clock-rotate-left"></i></div>
                        Order History
                    </a>

                    <a class="nav-link" href="{% url 'customer:product_status' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Product Status
                    </a>

                    <a class="nav-link" href="{% url 'customer:transactions' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-wallet"></i></div>
                        Transaction History
                    </a>

{#                    <a class="nav-link" href="{% url 'customer:change_info' %}">#}
{#                        <div class="sb-nav-link-icon"><i class="bi bi-gear-fill"></i></div>#}
{#                        Change Account Info#}
{#                    </a>#}


                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                {{ customer_name }}
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4 mt-4">

                {% block customer_home %}
                {% endblock %}

                {% block ordered_product_status %}
                {% endblock %}

                {% block transactions %}
                {% endblock %}

                {% block buying_history %}
                {% endblock %}

                {% block change_account_info %}
                {% endblock %}

            </div>
        </main>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>

{#<script src="{% static 'global_controller/js/base.js' %}"></script>#}
<script src="{% static 'customer/js/ajax.js' %}"></script>


<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{#<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.26/sweetalert2.min.js"></script>#}
</body>

</html>

templates/base/deliveryman_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>Deliveryman</title>
    <!--- jQuery CDN --->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '/global_controller/css/base.css' %}">
    <!--- Bootstrap 5.2.0 cdn --->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>
    <!--- Fontawesome cdn for icon--->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!--- Leaflet cdn for maps --->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
          integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
          crossorigin=""/>
</head>

<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'global_home' %}">Bengal Bay</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href=""><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <span class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">

        </span>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <a type="button" class="btn btn-danger" href="{% url 'logout' %}"><i class="bi bi-box-arrow-left me-2"></i>Log
            Out</a>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">

                    <a class="nav-link" href="{% url 'deliveryman:home' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Pickup Details
                    </a>

                    <a class="nav-link" href="{% url 'deliveryman:delivery-details' %}">
                        <div class="sb-nav-link-icon"><i class="bi bi-receipt"></i></div>
                        Delivery Details
                    </a>

                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                {{ deliveryman_name }}
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4 mt-4">

                {% block deliveryman_home %}
                {% endblock %}

                {% block delivery_details_of_customer %}
                {% endblock %}

                {% block delivery_details %}
                {% endblock %}

            </div>
        </main>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'global_controller/js/base.js' %}"></script>
{# ------ sweet alert 2 cdn -------- #}
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


</body>

</html>

templates/base/employee_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Hub Activity</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static '/global_controller/css/base.css' %}">

    {#---Font Awesome Icons CDN ------#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

</head>

<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'global_home' %}">Bengal Bay</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <span class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">

        </span>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <a type="button" class="btn btn-danger" href="{% url 'logout' %}"><i class="bi bi-box-arrow-left me-2"></i>Log
            Out</a>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">

                    <a class="nav-link" href="{% url 'employee:home' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Product Recieve local
                    </a>
                    <a class="nav-link" href="{% url 'employee:shipmentreceive' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Product Recieve global
                    </a>
                    <a class="nav-link" href="{% url 'employee:shipmentsend' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Product Shipment global
                    </a>
                    <a class="nav-link" href="{% url 'employee:localdelivery' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Product Shipment local
                    </a>

                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                {{ employee_name }}
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4 mt-4">

                {% block employee_home %}
                {% endblock %}
                {% block employee_home2 %}
                {% endblock %}

            </div>
        </main>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>

{#<script src="{% static 'seller/js/home.js' %}"></script>#}
{#<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>#}

{# sweetalert 2#}
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>

</html>

templates/base/popup_notification.html
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" id="toast_id" data-bs-autohide="true">
        <div class="toast-header">
            <strong class="me-auto text-success" id="notification_head_strong_id">

            </strong>

            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body" id="notification_body_id">

        </div>
    </div>
</div>

templates/base/seller_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Seller</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static '/global_controller/css/base.css' %}">

    {#---Font Awesome Icons CDN ------#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

</head>

<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'global_home' %}">Bengal Bay</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <span class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">

        </span>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <a type="button" class="btn btn-danger" href="{% url 'logout' %}"><i class="bi bi-box-arrow-left me-2"></i>Log
            Out</a>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">

                    <a class="nav-link" href="{% url 'seller:home' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-boxes-stacked"></i></div>
                        Inventory
                    </a>

                    <a class="nav-link" href="{% url 'seller:add_products' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-plus"></i></div>
                        Add a Product
                    </a>

                    <a class="nav-link" href="{% url 'seller:current_order' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-tachometer-alt"></i></div>
                        Current Order
                    </a>

                    <a class="nav-link" href="{% url 'seller:order_history' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-clock-rotate-left"></i></div>
                        Order History
                    </a>

                    <!-- <a class="nav-link" href="{% url 'seller:transaction-history' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-wallet"></i></div>
                        Transactions
                    </a> -->



                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                {{ seller.shop_name }}
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4 mt-4">

                {% block seller_home %}
                {% endblock %}

                {% block transaction_history %}
                {% endblock %}

            </div>
        </main>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>

{#<script src="{% static 'seller/js/home.js' %}"></script>#}
<script src="{% static 'seller/js/current_order.js' %}"></script>
{#<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>#}

{# sweetalert 2#}
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>

</html>