cse408ebay/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
import customer
import global_controller.views as global_view
import customer.views as customer_views
import global_controller.authentication_module
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', global_view.home, name='global_home'),
    path('customer/', include('customer.urls', namespace='customer')),
    path('employee/', include('employee.urls', namespace='employee')),
    path('seller/', include('seller.urls', namespace='seller')),
    path('deliveryman/', include('deliveryman.urls', namespace='deliveryman')),

    path('login/', global_controller.authentication_module.logIn, name='login'),
    path('register/', global_controller.authentication_module.register, name='register'),
    path('seller_register/', global_controller.authentication_module.seller_register, name='seller_register'),
    path("logout/", global_controller.authentication_module.logout_request, name="logout"),
    path("product-details/<slug:inventory_id>", global_view.product_details, name="product-details"),
    path("auction-product-details/<slug:auction_id>", global_view.auction_product_details,
         name="auction-product-details"),
    path("add_to_cart/", global_view.add_to_cart, name="add_to_cart"),
    path('auction/', global_view.auction_home, name='auction_home'),
    # customer stuffs
    path("buy_product/", customer.views.buy_product, name="buy_product"),
    path("seller_register/get_location_from_coordinate/",
         global_controller.authentication_module.get_address_from_coordinate, name='coordinate-to-address'),
    path("send-mail", global_controller.authentication_module.test_mail, name='send-mail'),
    path("place-bid", global_controller.views.place_bid, name='place-bid'),
    path("search", global_controller.views.search_module, name='search'),

    path("category/<slug:category_name>", global_controller.views.category_module, name='category'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path, include
from . import views

app_name = 'seller'

urlpatterns = [
    path('', views.load_inventory, name='home'),
    path("test_function/", views.test_functioon, name="test_function"),
    path("order_history/", views.order_history, name="order_history"),
    path("current_order/", views.current_order, name="current_order"),
    path("add_products/", views.add_products, name="add_products"),
    path("auction/", views.auction, name="auction"),
    path("wallet_to_bank/", views.wallet_to_bank, name="wallet_to_bank"),
    path("current_order/confirm_deliveryman/", views.confirm_deliveryman, name="confirm_deliveryman"),
    path("product_register/", views.product_register, name="product_register"),
    path("transcation-history/", views.transaction_history, name="transaction-history"),
    path("auction-multiple-product/", views.auction_multiple_product, name="auction-multiple-product"),
    path("restock-inventory/", views.restock_inventory, name="restock-inventory"),

]

seller/views.py
from itertools import product
from unicodedata import category
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
import json
import random
from datetime import date
from global_controller.models import *
from django.core.files.storage import FileSystemStorage
from django.core.cache import cache
from django.urls import reverse


def generate_otp():
    otp = ""
    for i in range(0, 6):
        x = random.randint(0, 61)
        if x < 26:
            otp += chr(x + 97)
        elif x < 52:
            otp += chr(x - 26 + 65)
        else:
            otp += chr(x - 52 + 48)
    return otp


# Create your views here.
def load_order_history(request):
    pass


def load_inventory(request):
    # This variable is used to display the current wallet amount of the seller.
    seller = Seller.objects.get(phone=request.session['phone_num'])
    print(seller)
    current_wallet = seller.wallet
    inventory = Inventory.objects.filter(seller__name=request.session['username'])
    # seller = Seller.objects.get(phone=request.session['phone_num'])
    ordered = Order.objects.filter(seller=seller, status__status="In Shop").count()
    delivered = Order.objects.filter(seller=seller, status__status="Delivered").count()
    returned = Order.objects.filter(seller=seller, status__status="Returned").count()
    auction = Auction.objects.filter(seller=seller).count()
    # spent =
    # wallet
    context = {
        'inventories': inventory,
        'current_wallet': current_wallet,
        'seller': seller,
        'ordered': ordered,
        'delivered': delivered,
        'returned': returned,
        'auction': auction
    }
    print(inventory)
    return render(request, 'seller/home.html', context)


def test_functioon(request):
    print(request.POST)
    return JsonResponse({})


def add_products(request):
    context = {}
    return render(request, 'seller/add_products.html', context)


def current_order(request):
    # the username is the phone number of the user.

    seller_phone = request.session['phone_num']

    # orders = Order.objects.filter(seller__phone=seller_phone)
    orders = Order.objects.filter(seller__phone=seller_phone, status__status='In Shop').order_by('-order_set__date')
    # orders = Order.objects.filter(seller__phone=seller_phone, status__status == 'In Shop').order_by('-order_set__date')

    print(orders)
    context = {
        'orders': orders
    }
    return render(request, 'seller/current_order.html', context)


def order_history(request):
    seller = Seller.objects.get(phone=request.session['phone_num'])
    orders = Order.objects.filter(seller=seller).exclude(status__status='In Shop').order_by('-order_set__date')
    print(orders)
    context = {
        'orders': orders
    }
    return render(request, 'seller/order_history.html', context)


def auction(request):
    # Fetch data from GET request
    start = request.GET['start']
    end = request.GET['end']
    quantity = request.GET['quantity']
    price = request.GET['price']
    inv_id = request.GET['inventory_id']

    # Fetch seller from session for creating new auction object
    seller = Seller.objects.get(phone=request.session['phone_num'])

    # Fetch and update inventory
    inventory = Inventory.objects.get(id=inv_id)
    inventory.quantity = int(inventory.quantity) - int(quantity)
    inventory.save()

    # Create new auction object and save to DB
    auction = Auction(seller=seller, start_time=start, end_time=end,
                      base_price=price, auction_name=inventory.product.name)

    context = {
        'status': 1,
    }
    if auction.start_time > auction.end_time:
        context['status'] = 0
        print("auction time mismatch")
    else:
        auction.save()
        newPackageItem = PackageItem(auction=auction, inventory=inventory, quantity=quantity)
        newPackageItem.save()
        print("auction added")

    return JsonResponse(context)


# Authenticated deliveryman for a corresponding order.
def confirm_deliveryman(request):
    otp = request.GET['otp']
    order_id = request.GET['order_id']

    order = Order.objects.get(id=order_id)
    # status
    #          1 ---- otp matched
    #          2 ---- otp did not match
    if order.OTP == otp:
        order_status = "Picked Up"
        order_status_obj = Order_Status.objects.get(status=order_status)

        order.status = order_status_obj
        order.OTP = generate_otp()
        order.save()

        status = 1
    else:
        status = 2
    context = {
        'status': status,
    }
    return JsonResponse(context)


# This method is used to make a transaction between the bank and the seller.
# It is done using the 'TRANSACTION' table and the 'wallet' attribute fo the
# current seller. The seller information is fetched from the session variable.
def wallet_to_bank(request):
    # This is amount is used to update the wallet amount in the wallet card of
    # the seller.

    amount = request.GET['amount']

    # update seller wallet
    seller = Seller.objects.get(phone=request.session['phone_num'])
    seller.wallet = int(seller.wallet) - int(amount)
    seller.save()

    # transaction = Transaction(type='RECHARGE', amount=amount)
    # transaction.save()
    # print(f"Transaction saved {transaction}")

    # ord_set = Order_Set(customer=seller,date=date.todya(), transaction=transaction)
    # ord_set.save()
    current_wallet = seller.wallet

    context = {
        'status': 1,
        'current_wallet': current_wallet,
    }
    return JsonResponse(context)


def product_register(request):
    context = {}
    print(request)
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        quantity = request.POST['quantity']
        warranty = request.POST['warranty']
        br = request.POST['brand']
        cat = request.POST['category']
        desc = request.POST['description']
        product_image = request.FILES['image_select']

        new_brand, created = Brand.objects.get_or_create(name=br)

        cat = cat.lower().capitalize()
        new_cat, created = Category.objects.get_or_create(name=cat)

        brand = Brand.objects.get(name=br)
        category = Category.objects.get(name=cat)
        new_product = Product(name=name, brand=brand, category=category, warranty=warranty, description=desc,
                              price=price)
        new_product.save()

        seller = Seller.objects.get(phone=request.session['phone_num'])
        new_inv = Inventory(seller=seller, product=new_product, quantity=quantity, inventory_image=product_image)
        new_inv.save()

        print("seller register : seller saved to db")
        print(f'{new_product} -- successfully registered')
    return redirect(reverse('seller:home'))


def transaction_history(request):
    return render(request, 'seller/transaction_history.html', {})


# Package auction
def auction_multiple_product(request):
    print(request.GET)
    pydict = request.GET.dict()
    print(pydict)
    # print(f"len of inventories -- {len(request.GET['inventoryidlst[]'])}")
    # print(f"len of qunantities -- {len(request.GET['quantitylst[]'])}")

    inventory_id_lst = json.loads(request.GET['inventoryidlst'])
    quantity_lst = json.loads(request.GET['quantitylst'])
    start_time = request.GET['start_time']
    end_time = request.GET['end_time']
    base_price = request.GET['base_price']
    package_name = request.GET['package_name']

    print(inventory_id_lst)
    print(quantity_lst)
    print(start_time)
    print(end_time)
    print(base_price)

    print("aaaaaaaaa")

    for i in range(0, len(quantity_lst)):
        actualcnt = Inventory.objects.get(id=inventory_id_lst[i]).quantity
        if int(quantity_lst[i]) >= actualcnt or int(quantity_lst[i]) <= 0:
            context = {
                'status': 0,
            }
            print("quantity is invalid")
            return JsonResponse(context)

    seller = Seller.objects.get(phone=request.session['phone_num'])
    new_auction = Auction(seller=seller, start_time=start_time, end_time=end_time,
                          base_price=base_price, auction_name=package_name)
    new_auction.save()

    for i in range(0, len(inventory_id_lst)):
        cur_inventory = Inventory.objects.get(id=inventory_id_lst[i])
        newPackageItem = PackageItem(inventory=cur_inventory, auction=new_auction, quantity=quantity_lst[i])
        newPackageItem.save()

    print("new package auction made")
    context = {
        'status': 1,
    }
    return JsonResponse(context)


def restock_inventory(request):
    quantity = request.GET['restock']
    inventory_id = request.GET['inventory_id']

    inventory = Inventory.objects.get(id=inventory_id)

    # update inventory
    inventory.quantity = int(inventory.quantity) + int(quantity)
    inventory.save()

    context = {
        'restocked_quantity': inventory.quantity
    }
    return JsonResponse(context)

templates/seller/add_auction.html
{% extends 'base/seller_base.html' %}
{% load static %}

{% block seller_home %}
    <style>
        /* Chrome, Safari, Edge, Opera */
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        /* Firefox */
        input[type=number] {
            -moz-appearance: textfield;
        }
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #ffffff !important;
        }

        .user_card {
            width: 700px;
            margin-top: auto;
            margin-bottom: auto;
            background: #a370f7;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #7649f9 !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
    </style>

    {% include 'seller/summary_cards.html' %}
    <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER A PRODUCT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

    <form class="row g-3">
  <div class="col-12">
    <label for="name" class="form-label">Product Name</label>
    <input type="text" class="form-control" id="name" placeholder="Product Name">
  </div>
  <div class="col-md-3">
    <label for="price" class="form-label">Price</label>
    <input type="number" class="form-control" id="price" placeholder="Price">
  </div>
        <div class="col-md-3">
    <label for="quantity" class="form-label">Quantity</label>
    <input type="number" class="form-control" id="quantity" placeholder="Quantity">
  </div>
  <div class="col-md-3">
    <label for="warranty" class="form-label">Warranty</label>
    <input type="number" class="form-control" id="warranty" placeholder="Warranty">
  </div>
  <div class="col-md-6">
    <label for="brand" class="form-label">Brand</label>
    <input type="text" class="form-control" id="brand" placeholder="Brand">
  </div>

  <div class="col-12">
    <label for="description" class="form-label">Description</label>
    <input type="text" class="form-control" id="description" placeholder="Description">
  </div>
  <div>
    <label for="imageselect" class="form-label">Add Images of product</label>
    <input class="form-control" type="file" id="imageselect" multiple>
  </div>



  <div class="col-12">

    <button type="submit" class="btn btn-primary">Add Product</button>
  </div>
</form>

    </div>


        </div>
    </div>
</div>
    <script src="{% static 'seller/js/home.js' %}"></script>

{% endblock %}

templates/seller/add_products.html
{% extends 'base/seller_base.html' %} 
{% load static %} 
{% block seller_home %}
<style>
    /* Chrome, Safari, Edge, Opera */
    
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
    /* Firefox */
    
    input[type=number] {
        -moz-appearance: textfield;
    }
    
    body,
    html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: #ffffff !important;
    }
    
    .user_card {
        width: 700px;
        margin-top: auto;
        margin-bottom: auto;
        background: #a370f7;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;
    }
    
    .form_container {
        margin-top: 20px;
    }
    
    #form-title {
        color: #fff;
    }
    
    .login_btn {
        width: 100%;
        background: #7649f9 !important;
        color: white !important;
    }
    
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    
    .login_container {
        padding: 0 2rem;
    }
    
    .input-group-text {
        background: #f7ba5b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }
    
    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
</style>

<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER A PRODUCT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
            <form method="POST" class="row g-3" action="{%url 'seller:product_register' %}" enctype="multipart/form-data">
                {% csrf_token %}
            <div class="col-12">
                <label for="name" class="form-label">Product Name</label>
                <input type="text" class="form-control" name="name" placeholder="Product Name">
            </div>
            <div class="col-md-3">
                <label for="price" class="form-label">Price</label>
                <input type="number" class="form-control" name="price" placeholder="Price">
            </div>
                    <div class="col-md-3">
                <label for="quantity" class="form-label">Quantity</label>
                <input type="number" class="form-control" name="quantity" placeholder="Quantity">
            </div>
            <div class="col-md-3">
                <label for="warranty" class="form-label">Warranty</label>
                <input type="number" class="form-control" name="warranty" placeholder="Warranty">
            </div>
            <div class="col-md-6">
                <label for="brand" class="form-label">Brand</label>
                <input type="text" class="form-control" name="brand" placeholder="Brand">
            </div>
                
            <div class="col-md-6">
                <label class="form-label" for="category" searchable="Find...">Category2</label>
                <select class="form-select" name="category">
                    <option selected disabled>Choose...</option>
                    <optgroup label="Home Utility">  
                        <option value="HomeDecor">Home Decor</option>
                        <option value="Bedding">Bedding</option>
                        <option value="Furniture">Furniture</option>
                        <option value="Kitchenware">Kitchenware</option>
                        <option value="Garden">Garden Items</option>
                        <option value="Groceries">Groceries</option>
                        <option value="Lamp">Lamp and Lighting</option>
                        <option value="Refrigerators">Rerigerators</option>
                        <option value="WashingMachine">Washing Machine</option>
                        <option value="AC">Air Conditioner</option>
                    </optgroup>

                    <optgroup label="Computer Accessories">  
                        <option value="Casing">Casing</option>
                        <option value="Cooler">Cooler</option>
                        <option value="GPU">Graphics Card</option>
                        <option value="Keyboard">Keyboard</option>
                        <option value="Monitor">Monitor</option>
                        <option value="Motherboard">Motherboard</option>
                        <option value="Mouse">Mouse</option>
                        <option value="PSU">Power Supply</option>
                        <option value="Processor">Processor</option>
                        <option value="Storage">Storage</option>
                    </optgroup>

                    <optgroup label="Fashion">  
                        <option value="Bags">Bags</option>
                        <option value="Clothing">Clothing</option>
                        <option value="Jewellery">Jewellery</option>
                        <option value="Luggage">Luggage</option>
                        <option value="Wallet">Wallet</option>
                        <option value="Watches">Watches  </option>
                    </optgroup>

                    <optgroup label="Electronics">  
                        <option value="Camera">Camera</option>
                        <option value="Phones">Phones</option>
                        <option value="Console">Console</option>
                        <option value="Drones">Drones</option>
                        <option value="TV">TV</option>
                        <option value="Vehicle">Vehicle</option>
                    </optgroup>

                    <optgroup label="Health">  
                        <option value="Eyecare">Eyecare</option>
                        <option value="Hair">Hair</option>
                        <option value="Makeup">Makeup</option>
                        <option value="Fragrance">Fragrance</option>
                    </optgroup>

                    <optgroup label="Sports">  
                        <option value="Cycling">Cycling</option>
                        <option value="Fishing">Fishing</option>
                        <option value="Fitness">Fitness</option>
                        <option value="Indoor">Indoor</option>
                        <option value="Outdoor">Outdoor</option>
                    </optgroup>       
                </select>
            </div>

            <div class="col-12">
                <label for="description" class="form-label">Description</label>
                <input type="text" class="form-control" name="description" placeholder="Description">
            </div>
            <div>
                <label for="imageselect" class="form-label">Add Images of product</label>
                <input class="form-control" type="file" name="image_select">
            </div>



            <div class="col-12">

            <button type="submit" class="btn btn-primary"> Add Product</button>
        </div>
        </form>

    </div>


            </div>

        </div>
</div>
</div>
<script src="{% static 'seller/js/home.js' %}"></script>

{% endblock %}

templates/seller/auction_form.html
<div class="modal fade" id="auction_form_modal" aria-hidden="true" aria-labelledby="exampleModalToggleLabel"
     tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header d-block">
                <h5 class="modal-title text-center" id="exampleModalToggleLabel">Auction Form</h5>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <h5 id="product_name_id">
                        Product Name
                    </h5>
                </div>

                <div class="row g-2 my-1">

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="datetime-local" class="form-control auction-date" id="start_time_id"
                                   placeholder="name@example.com" min="2022-08-13">
                            <label for="start_time_id">Start Time</label>
                        </div>
                    </div>

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="datetime-local" class="form-control" id="end_time_id"
                                   placeholder="name@example.com" value="mdo@example.com">
                            <label for="end_time_id">End Time</label>
                        </div>
                    </div>

                </div>

                <div class="row g-2">

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="number" class="form-control" id="base_price_id"
                                   placeholder="name@example.com">
                            <label for="floatingInputGrid">Base Price</label>
                        </div>
                    </div>

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="number" class="form-control" id="auction_quantity"
                                   placeholder="name@example.com" value="mdo@example.com">
                            <label for="floatingInputGrid">Quantity</label>
                        </div>
                    </div>

                </div>

            </div>
            <div class="modal-footer d-block">

                <div class="text-center">
                    <button class="btn btn-primary" id="btn_auction_proceed_id" data-bs-toggle="modal" data-bs-target="#auction_form_confirmation_modal">Proceed</button>
                </div>

            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="auction_form_confirmation_modal" aria-hidden="true" aria-labelledby="exampleModalToggleLabel"
     tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header d-block">
                <h5 class="modal-title text-center" id="exampleModalToggleLabel">Auction Confirmation</h5>
            </div>

            <div class="modal-body">
                <p>The following items will be auctioned. Do you want to continue?</p>

                <p id="auction_product_name_id">Product Name</p>
                <div class="row my-1">
                    <div class="col">
                        <p>Start Time : <strong id="final_auction_start">time start</strong></p>
                    </div>
                    <div class="col">
                        <p>End Time : <strong id="final_auction_end">end time</strong></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <p>Quantity : <strong id="final_auction_quantity">51</strong></p>
                    </div>
                    <div class="col">
                        <p>Base Price : <strong id="final_auction_base_price">3544</strong></p>
                    </div>
                </div>
            </div>

            <div class="modal-footer d-block">

                <div class="text-center">
                    <button class="btn btn-primary" id="btn-auction-confirmation-id" data-bs-dismiss="modal">Yes</button>
                    <button class="btn btn-primary" data-bs-dismiss="modal">No</button>
                </div>

            </div>
        </div>
    </div>
</div>

templates/seller/auction_package_multiple.html
<div class="modal fade" id="auction_package_modal" aria-hidden="true" aria-labelledby="exampleModalToggleLabel"
     tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header d-block">
                <h5 class="modal-title text-center" id="exampleModalToggleLabel">Auction Package</h5>
            </div>
            <div class="modal-body">
                <div class="row g-2">

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="package_name_id"
                                   placeholder="name@example.com" required>
                            <label for="floatingInputGrid">Package Name</label>
                        </div>
                    </div>


                </div>

                <div class="row g-2 my-1">

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="datetime-local" class="form-control auction-date" id="package_start_time_id"
                                   placeholder="name@example.com" min="2022-08-13" required>
                            <label for="start_time_id">Start Time</label>
                        </div>
                    </div>

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="datetime-local" class="form-control" id="package_end_time_id"
                                   placeholder="name@example.com" value="mdo@example.com" required>
                            <label for="end_time_id">End Time</label>
                        </div>
                    </div>

                </div>

                <div class="row g-2">

                    <div class="col-md">
                        <div class="form-floating">
                            <input type="number" class="form-control" id="package_base_price_id"
                                   placeholder="name@example.com" required>
                            <label for="floatingInputGrid">Base Price</label>
                        </div>
                    </div>


                </div>

            </div>
            <div class="modal-footer d-block">

                <div class="text-center">
                    <button class="btn btn-primary" onclick="test_function()"
                            id="btn_auction_proceed_id"
                            data-bs-toggle="modal"
                            data-bs-dismiss="modal"
                            data-bs-target="#auction_package_confirmation">Confirm
                    </button>
                </div>

            </div>
        </div>
    </div>
</div>